config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root "conversations#index"
  end
  resources :tracks
  resources :artists
  resources :albums
  resources :conversations
  resources :comments

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :group
  has_many :comments
  validates :name, presence: true
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @conversations = Conversation.all
  end

  def new
    @conversation = Conversation.new
  end

  def show
    @conversation = Conversation.find(params[:id])
    @comments = @conversation.comments.all
  end

  def edit
    @conversation = Conversation.find(params[:id])
  end

  def create
    @conversation = Conversation.new(conversation_params)
    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    def conversation_params
      params.require(:conversation).permit(:name)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Conversations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><strong><%= conversation.name %></strong></td>
        <td><%= link_to 'Show', conversation, class: 'button radius small' %></td>
        <td><%= link_to 'Edit', edit_artist_path(conversation), class: 'button radius small' %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete,
                                                 data: { confirm: 'Are you sure?' },
                                                 class: 'button radius small' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path%>

app/views/conversations/show.html.erb
<div class="row small-10">
  <p id="notice"><%= notice %></p>

  <h2>
    <strong><%= @conversation.name %></strong>
  </h2>

  <% if @conversation.comments.any? %>
      <h3>Comments (<%= @conversation.comments.count %>)</h3>
      <ol class="comments">
          <%= render @comments %>
      </ol>
  <% end %>

  <%= link_to 'Edit', edit_conversation_path(@conversation), class: 'button radius small' %> |
  <%= link_to 'Back', conversations_path, class: 'button radius small' %>
</div>